# Server设置
[server]
    Address    = ":7987"

[database]
    [[database.default]]
            host         = "127.0.0.1"
            port         = "3306"
            user         = "root"
            pass         = "root"
            name         = "alleria"
            type         = "mysql"